/**
 * Generates src/presentation/_shared/styles/global.css from the design token
 * source of truth (src/presentation/_shared/design/tokens.ts).
 *
 * The CSS variables here are consumed by tailwind.config.js as hsl(var(--x)) and
 * resolved by NativeWind. Runtime TS constants live in tokens.ts directly; this
 * script only keeps the CSS layer in sync. Run via `npm run tokens`.
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { CSS_VARS, CSS_VARS_LIGHT } from "../src/presentation/_shared/design/tokens";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "../src/presentation/_shared/styles/global.css");

function block(vars: Record<string, string>): string {
  return Object.entries(vars)
    .map(([name, value]) => `    --${name}: ${value};`)
    .join("\n");
}

const css = `@tailwind base;
@tailwind components;
@tailwind utilities;

/* GENERATED by scripts/generate-design-tokens.ts — edit design/tokens.ts, then \`npm run tokens\`. */
@layer base {
  :root {
${block(CSS_VARS)}
  }

  .light:root {
${block(CSS_VARS_LIGHT)}
  }

  .dark:root {
${block(CSS_VARS)}
  }
}
`;

writeFileSync(OUT, css, "utf8");
console.log(`✓ Wrote ${OUT}`);
