/**
 * dayDetailFixture — typed example payloads for `DayDetailView`, keyed by dayId,
 * doubling as the contract proposal for `GET /training/days/{id}/detail`. Layer-
 * neutral. Mirrors the handoff's `RD_PLANS` for the active PPL block, so every
 * tappable day in the routine detail opens a real plan.
 *
 * TEMPORARY: served by the repository stub until the endpoint ships.
 */
import type { DayType } from "../models/RoutineDashboard";
import type { DayDetailView, DayExerciseItem } from "../models/DayDetailView";

/** es-ES slug, matching the handoff's `rdSlug` (links to the exercise detail). */
function slug(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

// [name, muscle, equipment, sets, repRange, rir, rest, target, lastResult, progression|null, isKey]
type Row = [
  string,
  string,
  string,
  number,
  string,
  number,
  string,
  string,
  string,
  string | null,
  boolean
];

function toItems(rows: Row[]): DayExerciseItem[] {
  return rows.map(
    (
      [
        name,
        muscle,
        equipment,
        sets,
        repRange,
        rir,
        rest,
        target,
        lastResult,
        progression,
        isKey,
      ],
      i
    ) => ({
      exerciseId: slug(name),
      index: i + 1,
      name,
      isKey,
      muscle,
      equipment,
      target,
      sets,
      repRange,
      rir,
      rest,
      lastResult,
      progression,
    })
  );
}

const VOL_EST: Record<string, string> = {
  push: "7,1 t",
  pull: "6,8 t",
  legs: "9,2 t",
};

const NOTE: Record<string, string> = {
  push: "Día de empuje. El press banca es el ejercicio principal — busca 82,5 kg limpias a RIR 2. El resto, técnica y congestión.",
  pull: "Día de tirón. Mantén la dominada estricta y deja medio depósito en el remo: el sábado vamos a por PR.",
  legs: "Día clave de la semana. La sentadilla a 142,5 kg es PR de carga — calienta sin prisa y respeta el RIR 2.",
};

type DaySeed = {
  dayId: string;
  type: DayType;
  name: string;
  dayOfWeek: string;
  focus: string;
  dayNumber: number;
  estimateMin: number;
  rows: Row[];
};

const SEEDS: DaySeed[] = [
  {
    dayId: "push-a",
    type: "push",
    name: "Push A",
    dayOfWeek: "Lun",
    focus: "Pecho · hombros · tríceps",
    dayNumber: 1,
    estimateMin: 62,
    rows: [
      [
        "Press banca",
        "Pecho",
        "Barra",
        4,
        "6–8",
        2,
        "2:30",
        "82,5 kg",
        "80 kg × 8",
        "+2,5",
        true,
      ],
      [
        "Press inclinado mancuerna",
        "Pecho sup.",
        "Mancuerna",
        3,
        "8–10",
        2,
        "2:00",
        "34 kg",
        "32 kg × 9",
        "+2",
        false,
      ],
      [
        "Press militar",
        "Hombro",
        "Barra",
        4,
        "8",
        2,
        "2:00",
        "55 kg",
        "52,5 kg × 8",
        "+2,5",
        false,
      ],
      [
        "Aperturas en polea",
        "Pecho",
        "Polea",
        3,
        "12–15",
        1,
        "1:30",
        "18 kg",
        "16 kg × 14",
        null,
        false,
      ],
      [
        "Elevaciones laterales",
        "Deltoides",
        "Mancuerna",
        4,
        "12–15",
        1,
        "1:00",
        "12 kg",
        "12 kg × 13",
        null,
        false,
      ],
      [
        "Extensión de tríceps en polea",
        "Tríceps",
        "Polea",
        3,
        "12",
        2,
        "1:30",
        "30 kg",
        "27,5 kg × 12",
        null,
        false,
      ],
    ],
  },
  {
    dayId: "pull-a",
    type: "pull",
    name: "Pull A",
    dayOfWeek: "Mar",
    focus: "Espalda · bíceps · deltoides post.",
    dayNumber: 2,
    estimateMin: 58,
    rows: [
      [
        "Dominadas lastradas",
        "Dorsal",
        "Peso corp.",
        4,
        "6–8",
        2,
        "2:30",
        "+20 kg",
        "+17,5 kg × 7",
        "+2,5",
        true,
      ],
      [
        "Remo con barra",
        "Espalda",
        "Barra",
        4,
        "8–10",
        2,
        "2:00",
        "80 kg",
        "77,5 kg × 9",
        "+2,5",
        false,
      ],
      [
        "Jalón al pecho",
        "Dorsal",
        "Polea",
        3,
        "10–12",
        2,
        "1:45",
        "65 kg",
        "62,5 kg × 11",
        null,
        false,
      ],
      [
        "Curl de bíceps",
        "Bíceps",
        "Mancuerna",
        3,
        "8–10",
        1,
        "1:30",
        "16 kg",
        "16 kg × 11",
        null,
        false,
      ],
      [
        "Face pull",
        "Deltoides post.",
        "Polea",
        3,
        "15",
        2,
        "1:00",
        "25 kg",
        "22,5 kg × 15",
        null,
        false,
      ],
    ],
  },
  {
    dayId: "legs-a",
    type: "legs",
    name: "Legs A",
    dayOfWeek: "Mié",
    focus: "Cuádriceps · glúteo · core",
    dayNumber: 3,
    estimateMin: 65,
    rows: [
      [
        "Sentadilla",
        "Cuádriceps",
        "Barra",
        4,
        "5–7",
        2,
        "3:00",
        "142,5 kg",
        "140 kg × 6",
        "+2,5",
        true,
      ],
      [
        "Peso muerto rumano",
        "Femoral",
        "Barra",
        3,
        "8–10",
        2,
        "2:30",
        "122,5 kg",
        "120 kg × 9",
        "+2,5",
        false,
      ],
      [
        "Prensa inclinada",
        "Cuádriceps",
        "Máquina",
        3,
        "10–12",
        2,
        "2:00",
        "220 kg",
        "210 kg × 11",
        null,
        false,
      ],
      [
        "Hip thrust",
        "Glúteo",
        "Barra",
        3,
        "10",
        2,
        "1:45",
        "105 kg",
        "100 kg × 12",
        "+5",
        false,
      ],
      [
        "Plancha",
        "Core",
        "Peso corp.",
        3,
        "45 s",
        1,
        "1:00",
        "45 s",
        "—",
        null,
        false,
      ],
    ],
  },
  {
    dayId: "push-b",
    type: "push",
    name: "Push B",
    dayOfWeek: "Jue",
    focus: "Hombro · tríceps · pecho sup.",
    dayNumber: 4,
    estimateMin: 55,
    rows: [
      [
        "Press militar",
        "Hombro",
        "Barra",
        4,
        "6–8",
        2,
        "2:30",
        "57,5 kg",
        "55 kg × 7",
        "+2,5",
        true,
      ],
      [
        "Press inclinado mancuerna",
        "Pecho sup.",
        "Mancuerna",
        4,
        "8–10",
        2,
        "2:00",
        "36 kg",
        "34 kg × 9",
        "+2",
        false,
      ],
      [
        "Fondos en paralelas",
        "Pecho inf.",
        "Peso corp.",
        3,
        "8–10",
        2,
        "2:00",
        "+10 kg",
        "+7,5 kg × 9",
        null,
        false,
      ],
      [
        "Elevaciones laterales",
        "Deltoides",
        "Mancuerna",
        4,
        "12–15",
        1,
        "1:00",
        "12 kg",
        "12 kg × 13",
        null,
        false,
      ],
      [
        "Extensión de tríceps en polea",
        "Tríceps",
        "Polea",
        3,
        "10–12",
        1,
        "1:30",
        "32,5 kg",
        "30 kg × 12",
        "+2,5",
        false,
      ],
    ],
  },
  {
    dayId: "pull-b",
    type: "pull",
    name: "Pull B",
    dayOfWeek: "Vie",
    focus: "Dorsal · trapecio · bíceps",
    dayNumber: 5,
    estimateMin: 54,
    rows: [
      [
        "Remo con barra",
        "Espalda",
        "Barra",
        4,
        "6–8",
        2,
        "2:30",
        "85 kg",
        "82,5 kg × 8",
        "+2,5",
        true,
      ],
      [
        "Jalón al pecho",
        "Dorsal",
        "Polea",
        4,
        "8–10",
        2,
        "2:00",
        "70 kg",
        "67,5 kg × 9",
        "+2,5",
        false,
      ],
      [
        "Remo en polea baja",
        "Espalda",
        "Polea",
        3,
        "10–12",
        2,
        "1:45",
        "62,5 kg",
        "60 kg × 11",
        null,
        false,
      ],
      [
        "Face pull",
        "Deltoides post.",
        "Polea",
        3,
        "15",
        2,
        "1:00",
        "27,5 kg",
        "25 kg × 15",
        "+2,5",
        false,
      ],
      [
        "Curl de bíceps",
        "Bíceps",
        "Mancuerna",
        3,
        "10–12",
        1,
        "1:15",
        "18 kg",
        "16 kg × 11",
        "+2",
        false,
      ],
    ],
  },
  {
    dayId: "legs-b",
    type: "legs",
    name: "Legs B",
    dayOfWeek: "Sáb",
    focus: "Femoral · glúteo · gemelo",
    dayNumber: 6,
    estimateMin: 66,
    rows: [
      [
        "Peso muerto rumano",
        "Femoral",
        "Barra",
        4,
        "6–8",
        2,
        "3:00",
        "125 kg",
        "122,5 kg × 8",
        "+2,5",
        true,
      ],
      [
        "Sentadilla",
        "Cuádriceps",
        "Barra",
        3,
        "8–10",
        2,
        "2:30",
        "120 kg",
        "117,5 kg × 9",
        "+2,5",
        false,
      ],
      [
        "Curl nórdico",
        "Femoral",
        "Peso corp.",
        3,
        "6–8",
        2,
        "2:00",
        "Peso corp.",
        "8 reps",
        null,
        false,
      ],
      [
        "Hip thrust",
        "Glúteo",
        "Barra",
        4,
        "10–12",
        1,
        "1:45",
        "110 kg",
        "105 kg × 12",
        "+5",
        false,
      ],
      [
        "Elevación de gemelo",
        "Gemelo",
        "Máquina",
        4,
        "12–15",
        1,
        "1:00",
        "92,5 kg",
        "90 kg × 15",
        null,
        false,
      ],
    ],
  },
];

function build(seed: DaySeed): DayDetailView {
  const exercises = toItems(seed.rows);
  return {
    header: {
      dayId: seed.dayId,
      type: seed.type,
      routineName: "PPL Hipertrofia",
      dayNumber: seed.dayNumber,
      trainingTotal: 6,
      name: seed.name,
      dayOfWeek: seed.dayOfWeek,
      focus: seed.focus,
      exercisesCount: exercises.length,
      setsCount: exercises.reduce((a, e) => a + e.sets, 0),
      estimateMin: seed.estimateMin,
      volumeEstimate: VOL_EST[seed.type] ?? "—",
    },
    isRest: false,
    restFocus: null,
    agentNote: NOTE[seed.type] ?? null,
    exercises,
  };
}

export const dayDetailFixtures: Record<string, DayDetailView> =
  Object.fromEntries(SEEDS.map((s) => [s.dayId, build(s)]));

/** Stub resolver: returns the day detail for `id`, falling back to the today's day. */
export function dayDetailFixtureFor(id: string): DayDetailView {
  return dayDetailFixtures[id] ?? dayDetailFixtures["legs-a"];
}
