/**
 * routineDetailFixture — typed example payloads for `RoutineDetailView`, keyed by
 * routine id, doubling as the contract proposal for
 * `GET /training/routines/{id}/detail`. Layer-neutral. Mirrors the handoff's
 * `rutinas-data` catalog (the active block + the two archived ones), so every card
 * in the library opens a real detail.
 *
 * TEMPORARY: served by the repository stub until the endpoint ships.
 */
import type { RoutineDetailView } from "../models/RoutineDetailView";

const pplHipertrofia: RoutineDetailView = {
  header: {
    id: "ppl-hipertrofia",
    name: "PPL Hipertrofia",
    state: "active",
    goal: "Hipertrofia",
    split: "Push · Pull · Legs",
    type: "push",
    contextLabel: "Última: Sáb 31 may",
    perWeek: 6,
    weeks: 6,
    adherencePct: 39,
    volumeTotal: "32,1 t",
    mesocycle: {
      id: "meso-acumulacion",
      name: "Acumulación",
      goal: "Volumen",
      orderIndex: 0,
      totalBlocks: 3,
      isLastWeek: false,
      isLastBlock: false,
    },
    week: 3,
    weekFraction: 3 / 7,
    sessionsDone: 14,
    sessionsPlanned: 36,
    volumeTrendPct: 8,
  },
  agentNote:
    "Tu mejor bloque hasta ahora: semana 3 y vas adelantado. Subió el volumen un 8 % y la sentadilla suma 12 kg de e1RM. Mantenemos PPL dos vueltas más y reevaluamos cargas.",
  days: [
    {
      dayId: "push-a",
      dayOfWeek: "Lun",
      name: "Push A",
      type: "push",
      focus: "Pecho · hombros · tríceps",
      exercisesCount: 6,
      setsCount: 21,
      estimate: "~62 min",
      status: "done",
      isToday: false,
    },
    {
      dayId: "pull-a",
      dayOfWeek: "Mar",
      name: "Pull A",
      type: "pull",
      focus: "Espalda · bíceps · deltoides post.",
      exercisesCount: 5,
      setsCount: 17,
      estimate: "~58 min",
      status: "done",
      isToday: false,
    },
    {
      dayId: "legs-a",
      dayOfWeek: "Mié",
      name: "Legs A",
      type: "legs",
      focus: "Cuádriceps · glúteo · core",
      exercisesCount: 5,
      setsCount: 16,
      estimate: "~65 min",
      status: "now",
      isToday: true,
    },
    {
      dayId: "push-b",
      dayOfWeek: "Jue",
      name: "Push B",
      type: "push",
      focus: "Hombro · tríceps · pecho sup.",
      exercisesCount: 5,
      setsCount: 18,
      estimate: "~55 min",
      status: "up",
      isToday: false,
    },
    {
      dayId: "pull-b",
      dayOfWeek: "Vie",
      name: "Pull B",
      type: "pull",
      focus: "Dorsal · trapecio · bíceps",
      exercisesCount: 5,
      setsCount: 17,
      estimate: "~54 min",
      status: "up",
      isToday: false,
    },
    {
      dayId: "legs-b",
      dayOfWeek: "Sáb",
      name: "Legs B",
      type: "legs",
      focus: "Femoral · glúteo · gemelo",
      exercisesCount: 5,
      setsCount: 18,
      estimate: "~66 min",
      status: "up",
      isToday: false,
    },
    {
      dayId: null,
      dayOfWeek: "Dom",
      name: "Descanso",
      type: "rest",
      focus: "Movilidad opcional · 10 min",
      exercisesCount: null,
      setsCount: null,
      estimate: null,
      status: "rest",
      isToday: false,
    },
  ],
  trainingDaysCount: 6,
  restDaysCount: 1,
  sessionsBlockCount: 14,
};

const pplBase: RoutineDetailView = {
  header: {
    id: "ppl-base",
    name: "PPL base",
    state: "completed",
    goal: "Hipertrofia",
    split: "Push · Pull · Legs",
    type: "push",
    contextLabel: "Finalizada · 1 mar 2026",
    perWeek: 6,
    weeks: 8,
    adherencePct: 92,
    volumeTotal: "41,8 t",
    mesocycle: null, // finished routine → no active block (tri-state null)
    week: 8,
    weekFraction: null,
    sessionsDone: 44,
    sessionsPlanned: 48,
    volumeTrendPct: 12,
  },
  agentNote:
    "Cerrada con un 91/100 de adherencia — 44 de 48 sesiones. La base que te dejó listo para el bloque actual. Volúmenes y PRs migrados a tu historial.",
  days: [
    {
      dayId: "push-a",
      dayOfWeek: "Lun",
      name: "Push A",
      type: "push",
      focus: "Pecho · hombros · tríceps",
      exercisesCount: 6,
      setsCount: 21,
      estimate: "~60 min",
      status: "done",
      isToday: false,
    },
    {
      dayId: "pull-a",
      dayOfWeek: "Mar",
      name: "Pull A",
      type: "pull",
      focus: "Espalda · bíceps · deltoides post.",
      exercisesCount: 5,
      setsCount: 17,
      estimate: "~56 min",
      status: "done",
      isToday: false,
    },
    {
      dayId: "legs-a",
      dayOfWeek: "Mié",
      name: "Legs A",
      type: "legs",
      focus: "Cuádriceps · glúteo · core",
      exercisesCount: 5,
      setsCount: 16,
      estimate: "~62 min",
      status: "done",
      isToday: false,
    },
    {
      dayId: "push-b",
      dayOfWeek: "Jue",
      name: "Push B",
      type: "push",
      focus: "Hombro · tríceps · pecho sup.",
      exercisesCount: 5,
      setsCount: 18,
      estimate: "~54 min",
      status: "done",
      isToday: false,
    },
    {
      dayId: "pull-b",
      dayOfWeek: "Vie",
      name: "Pull B",
      type: "pull",
      focus: "Dorsal · trapecio · bíceps",
      exercisesCount: 5,
      setsCount: 17,
      estimate: "~52 min",
      status: "done",
      isToday: false,
    },
    {
      dayId: "legs-b",
      dayOfWeek: "Sáb",
      name: "Legs B",
      type: "legs",
      focus: "Femoral · glúteo · gemelo",
      exercisesCount: 5,
      setsCount: 18,
      estimate: "~62 min",
      status: "done",
      isToday: false,
    },
  ],
  trainingDaysCount: 6,
  restDaysCount: 0,
  sessionsBlockCount: 44,
};

const iniciacionFullbody: RoutineDetailView = {
  header: {
    id: "iniciacion-fullbody",
    name: "Iniciación full-body",
    state: "completed",
    goal: "Adaptación",
    split: "Full body",
    type: "push",
    contextLabel: "Finalizada · 30 dic 2025",
    perWeek: 3,
    weeks: 4,
    adherencePct: 92,
    volumeTotal: "12,4 t",
    mesocycle: null, // flat / finished → no active block
    week: 4,
    weekFraction: null,
    sessionsDone: 11,
    sessionsPlanned: 12,
    volumeTrendPct: 6,
  },
  agentNote:
    "Tu primera rutina. Cuatro semanas de adaptación para fijar técnica antes de subir volumen. Misión cumplida: base sólida para todo lo que vino después.",
  days: [
    {
      dayId: "push-a",
      dayOfWeek: "Lun",
      name: "Full body A",
      type: "push",
      focus: "Pecho · hombros · tríceps",
      exercisesCount: 6,
      setsCount: 21,
      estimate: "~50 min",
      status: "done",
      isToday: false,
    },
    {
      dayId: "legs-a",
      dayOfWeek: "Mié",
      name: "Full body B",
      type: "legs",
      focus: "Cuádriceps · glúteo · core",
      exercisesCount: 5,
      setsCount: 16,
      estimate: "~52 min",
      status: "done",
      isToday: false,
    },
    {
      dayId: "pull-a",
      dayOfWeek: "Vie",
      name: "Full body C",
      type: "pull",
      focus: "Espalda · bíceps · deltoides post.",
      exercisesCount: 5,
      setsCount: 17,
      estimate: "~48 min",
      status: "done",
      isToday: false,
    },
  ],
  trainingDaysCount: 3,
  restDaysCount: 0,
  sessionsBlockCount: 11,
};

export const routineDetailFixtures: Record<string, RoutineDetailView> = {
  "ppl-hipertrofia": pplHipertrofia,
  "ppl-base": pplBase,
  "iniciacion-fullbody": iniciacionFullbody,
};

/** Stub resolver: returns the detail for `id`, falling back to the active block. */
export function routineDetailFixtureFor(id: string): RoutineDetailView {
  return routineDetailFixtures[id] ?? pplHipertrofia;
}
