/**
 * sessionFeedFixture — typed example page for `SessionFeedPage`. RAW / locale
 * neutral, mirroring `GET /api/v1/training/sessions-feed`: ISO instants, kg
 * volumes, second durations. Mirrors the handoff's `sesiones-data` (two recent
 * blocks); `type` is the platform `DayKind` (`workout`) — the push/pull/legs
 * muscle split was a design liberty, dropped on reconciliation. `nextCursor` is
 * null (a single page).
 *
 * TEST DATA ONLY: the repository now reads the live endpoint; this stays as the
 * fixture the unit tests assert against.
 */
import type { SessionFeedPage } from "../models/SessionFeed";

const kg = (value: number) => ({ value, unit: "kg" as const });

export const sessionFeedFixture: SessionFeedPage = {
  totalCount: 14,
  nextCursor: null,
  blocks: [
    {
      id: "ppl-hipertrofia",
      name: "PPL Hipertrofia",
      state: "active",
      dateRange: {
        start: "2026-05-12T12:00:00.000Z",
        end: "2026-05-31T12:00:00.000Z",
      },
      totalVolume: kg(174600),
      sessions: [
        {
          id: "legs-b-31may",
          completedAt: "2026-05-31T12:00:00.000Z",
          type: "workout",
          name: "Legs B",
          hasPR: true,
          prCount: 1,
          volume: kg(16300),
          volumeFraction: 0.96,
          durationSeconds: 3960,
        },
        {
          id: "pull-b-30may",
          completedAt: "2026-05-30T12:00:00.000Z",
          type: "workout",
          name: "Pull B",
          hasPR: false,
          prCount: 0,
          volume: kg(8600),
          volumeFraction: 0.51,
          durationSeconds: 3240,
        },
        {
          id: "push-b-29may",
          completedAt: "2026-05-29T12:00:00.000Z",
          type: "workout",
          name: "Push B",
          hasPR: true,
          prCount: 1,
          volume: kg(4800),
          volumeFraction: 0.28,
          durationSeconds: 3300,
        },
        {
          id: "legs-a-28may",
          completedAt: "2026-05-28T12:00:00.000Z",
          type: "workout",
          name: "Legs A",
          hasPR: false,
          prCount: 0,
          volume: kg(17000),
          volumeFraction: 1.0,
          durationSeconds: 3840,
        },
        {
          id: "pull-a-27may",
          completedAt: "2026-05-27T12:00:00.000Z",
          type: "workout",
          name: "Pull A",
          hasPR: false,
          prCount: 0,
          volume: kg(7000),
          volumeFraction: 0.41,
          durationSeconds: 3420,
        },
        {
          id: "push-a-26may",
          completedAt: "2026-05-26T12:00:00.000Z",
          type: "workout",
          name: "Push A",
          hasPR: true,
          prCount: 2,
          volume: kg(7400),
          volumeFraction: 0.44,
          durationSeconds: 3480,
        },
        {
          id: "legs-b-24may",
          completedAt: "2026-05-24T12:00:00.000Z",
          type: "workout",
          name: "Legs B",
          hasPR: false,
          prCount: 0,
          volume: kg(15600),
          volumeFraction: 0.92,
          durationSeconds: 3840,
        },
        {
          id: "pull-b-23may",
          completedAt: "2026-05-23T12:00:00.000Z",
          type: "workout",
          name: "Pull B",
          hasPR: false,
          prCount: 0,
          volume: kg(8200),
          volumeFraction: 0.48,
          durationSeconds: 3300,
        },
        {
          id: "push-b-22may",
          completedAt: "2026-05-22T12:00:00.000Z",
          type: "workout",
          name: "Push B",
          hasPR: false,
          prCount: 0,
          volume: kg(4600),
          volumeFraction: 0.27,
          durationSeconds: 3360,
        },
      ],
    },
    {
      id: "ppl-base",
      name: "PPL base",
      state: "completed",
      dateRange: {
        start: "2026-01-06T12:00:00.000Z",
        end: "2026-02-28T12:00:00.000Z",
      },
      totalVolume: kg(41800),
      sessions: [
        {
          id: "legs-b-28feb",
          completedAt: "2026-02-28T12:00:00.000Z",
          type: "workout",
          name: "Legs B",
          hasPR: false,
          prCount: 0,
          volume: kg(14100),
          volumeFraction: 0.95,
          durationSeconds: 3720,
        },
        {
          id: "pull-b-27feb",
          completedAt: "2026-02-27T12:00:00.000Z",
          type: "workout",
          name: "Pull B",
          hasPR: false,
          prCount: 0,
          volume: kg(7400),
          volumeFraction: 0.5,
          durationSeconds: 3120,
        },
        {
          id: "push-b-26feb",
          completedAt: "2026-02-26T12:00:00.000Z",
          type: "workout",
          name: "Push B",
          hasPR: true,
          prCount: 1,
          volume: kg(4200),
          volumeFraction: 0.28,
          durationSeconds: 3240,
        },
        {
          id: "legs-a-25feb",
          completedAt: "2026-02-25T12:00:00.000Z",
          type: "workout",
          name: "Legs A",
          hasPR: false,
          prCount: 0,
          volume: kg(14800),
          volumeFraction: 1.0,
          durationSeconds: 3600,
        },
        {
          id: "pull-a-24feb",
          completedAt: "2026-02-24T12:00:00.000Z",
          type: "workout",
          name: "Pull A",
          hasPR: false,
          prCount: 0,
          volume: kg(6800),
          volumeFraction: 0.46,
          durationSeconds: 3300,
        },
      ],
    },
  ],
};
